#! /usr/bin/env python3
from tabulate import tabulate

# EJERCICIO1

# Se quiere realizar una lista de la compra, para ello vamos a tener una tupla o par (x, y) que contenga como valor “x”
# el nombre del elemento y como valor “y” la cantidad de elementos.

listaCompra = {"Manzanas": 2, "Caja de cereales": 1, "Caja de chele": 1, "Huevos": 12, "Bollos de pan": 3,
               "Botelline": 48}
lista = [("algo", 1), ("algo", 3)]

print(tabulate(listaCompra.items(), headers=["comidas", "cantidades"]))

for comida, cantidad in listaCompra.items():
    print('\n', str(comida).ljust(15), '-->'.ljust(5), str(cantidad).ljust(5))
# Comando ljust(10) para ajustar el texto.
